In [1]:
import pretty_midi
import numpy as np


In [2]:
sr = 22050
min_midi = 21
max_midi = 108

mid_file = 'data/maps/test/AkPnCGdD/MAPS_MUS-chpn-p15_AkPnCGdD.mid'

In [3]:
midobj = pretty_midi.PrettyMIDI(mid_file)     # loadfile


In [33]:
mid = midobj.get_piano_roll(fs=sr)

In [34]:
mid.shape

(128, 6010931)

In [35]:
mid[mid>0] = 1
mid = mid.astype(np.int8)

In [28]:
mid.dtype

dtype('int32')

In [36]:
mid.astype(np.uint8)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [37]:
mid[:, 33451]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
midobj.instruments

[Instrument(program=0, is_drum=False, name="")]

In [11]:
midobj.get_tempo_changes()

(array([0.]), array([136.53741125]))

In [12]:
midobj.get_end_time()

272.60461312906284

In [13]:
midobj.estimate_tempi()

(array([165.6893469 , 161.49628011, 161.2287822 , 161.63983939,
        161.59027234, 161.56845331, 161.37319998, 160.37982942,
        161.5820596 , 165.47760044, 165.22958062, 165.01425014,
        160.55492449, 148.4609878 , 164.61958573, 160.38306914,
        150.19522044, 150.97703514, 161.52506876, 165.01222139,
        154.6902805 , 161.55423228, 160.02580182, 161.17302284,
        129.8322324 , 121.49581395, 161.00192005,  94.46026127,
        135.00064437, 121.99829173,  36.67118593,  75.86003382,
         72.5202839 , 148.84294878]),
 array([0.59919028, 0.06477733, 0.02699055, 0.0242915 , 0.02294197,
        0.02159244, 0.02024291, 0.01889339, 0.01754386, 0.01619433,
        0.01619433, 0.01619433, 0.0148448 , 0.01214575, 0.01214575,
        0.01214575, 0.01079622, 0.01079622, 0.00944669, 0.00809717,
        0.00674764, 0.00674764, 0.00539811, 0.00539811, 0.00539811,
        0.00404858, 0.00134953, 0.00134953, 0.00134953, 0.00134953,
        0.00134953, 0.00134953, 0.00134953

In [14]:
midobj.estimate_tempo()

165.68934689665198

In [15]:
midobj.get_beats()

array([  0.     ,   0.43944,   0.87888,   1.31832,   1.75776,   2.1972 ,
         2.63664,   3.07608,   3.51552,   3.95496,   4.3944 ,   4.83384,
         5.27328,   5.71272,   6.15216,   6.5916 ,   7.03104,   7.47048,
         7.90992,   8.34936,   8.7888 ,   9.22824,   9.66768,  10.10712,
        10.54656,  10.986  ,  11.42544,  11.86488,  12.30432,  12.74376,
        13.1832 ,  13.62264,  14.06208,  14.50152,  14.94096,  15.3804 ,
        15.81984,  16.25928,  16.69872,  17.13816,  17.5776 ,  18.01704,
        18.45648,  18.89592,  19.33536,  19.7748 ,  20.21424,  20.65368,
        21.09312,  21.53256,  21.972  ,  22.41144,  22.85088,  23.29032,
        23.72976,  24.1692 ,  24.60864,  25.04808,  25.48752,  25.92696,
        26.3664 ,  26.80584,  27.24528,  27.68472,  28.12416,  28.5636 ,
        29.00304,  29.44248,  29.88192,  30.32136,  30.7608 ,  31.20024,
        31.63968,  32.07912,  32.51856,  32.958  ,  33.39744,  33.83688,
        34.27632,  34.71576,  35.1552 ,  35.59464, 

In [18]:
midobj.estimate_beat_start()

2.8517801251258894

In [19]:
midobj.get_downbeats()

array([  0.     ,   1.75776,   3.51552,   5.27328,   7.03104,   8.7888 ,
        10.54656,  12.30432,  14.06208,  15.81984,  17.5776 ,  19.33536,
        21.09312,  22.85088,  24.60864,  26.3664 ,  28.12416,  29.88192,
        31.63968,  33.39744,  35.1552 ,  36.91296,  38.67072,  40.42848,
        42.18624,  43.944  ,  45.70176,  47.45952,  49.21728,  50.97504,
        52.7328 ,  54.49056,  56.24832,  58.00608,  59.76384,  61.5216 ,
        63.27936,  65.03712,  66.79488,  68.55264,  70.3104 ,  72.06816,
        73.82592,  75.58368,  77.34144,  79.0992 ,  80.85696,  82.61472,
        84.37248,  86.13024,  87.888  ,  89.64576,  91.40352,  93.16128,
        94.91904,  96.6768 ,  98.43456, 100.19232, 101.95008, 103.70784,
       105.4656 , 107.22336, 108.98112, 110.73888, 112.49664, 114.2544 ,
       116.01216, 117.76992, 119.52768, 121.28544, 123.0432 , 124.80096,
       126.55872, 128.31648, 130.07424, 131.832  , 133.58976, 135.34752,
       137.10528, 138.86304, 140.6208 , 142.37856, 

In [50]:
import numpy as np
np.unique(np.floor(midobj.get_onsets()*22050) - 11025)


array([      0.,    8888.,   13332.,   17954.,   27198.,   35572.,
         43789.,   51856.,   60363.,   69308.,   78254.,   86866.,
         95321.,  103437.,  111654.,  119872.,  128760.,  137823.,
        146599.,  150987.,  155518.,  164581.,  173247.,  181728.,
        189895.,  198670.,  207792.,  216396.,  224903.,  233410.,
        242241.,  251073.,  257871.,  260136.,  262954.,  265734.,
        268475.,  269923.,  271247.,  274165.,  277276.,  280778.,
        289902.,  294464.,  299086.,  308330.,  316837.,  325189.,
        333393.,  341900.,  350846.,  359791.,  368246.,  376700.,
        384954.,  393357.,  401760.,  410649.,  419712.,  428487.,
        432875.,  437407.,  446469.,  454738.,  462905.,  471517.,
        480293.,  489414.,  497973.,  506480.,  514987.,  523818.,
        532650.,  541370.,  550202.,  559446.,  568277.,  576836.,
        585239.,  593798.,  602356.,  611188.,  619908.,  628684.,
        636937.,  645444.,  654110.,  663172.,  672234.,  6808

In [27]:
1000/22050

0.045351473922902494

In [22]:
midobj.get_chroma()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
midobj.time_to_tick(0.0)

0

In [48]:
a = [1, 1, 34, 54, 6, 78, 89, 5, 4, 23, 4]
b = np.array(a)
b

array([ 1,  1, 34, 54,  6, 78, 89,  5,  4, 23,  4])

In [38]:
for i in b:
    print(i)

[ 1 34 54  6 78]
[89  5  4 23  4]


In [47]:
a.remove(1)


[34, 54, 6, 78, 89, 5, 4, 23, 4]

In [49]:
np.unique(a)

array([ 1,  4,  5,  6, 23, 34, 54, 78, 89])

In [51]:
1 in range(10)

True

In [61]:
b.astype(float).tolist()

[1.0, 1.0, 34.0, 54.0, 6.0, 78.0, 89.0, 5.0, 4.0, 23.0, 4.0]

In [41]:
import numpy as np 
a = [0, 0, 1, 1]
a = np.array(a)
np.where(a==1)

(array([2, 3]),)

In [40]:
import numpy
 
a = numpy.array(([3,2,1],[2,5,7],[4,7,8]))
 
itemindex = numpy.argwhere(a == 7)
 
print (itemindex)
 
print (a)


[[1 2]
 [2 1]]
[[3 2 1]
 [2 5 7]
 [4 7 8]]
